### ISSUE TITLE
FFmpeg path for FireDM version 2021.12.23

### ISSUE THREAD

**Issue by candrapersada** [Aboghazala/AwesomeTkinter#10]
why isn't this in the FFmpeg path?
![a](https://user-images.githubusercontent.com/36833664/147301358-bbd54528-39ff-43d4-9bef-b227f753ae2c.PNG)
![b](https://user-images.githubusercontent.com/36833664/147301385-6a070ce1-19d2-42bc-a5fa-6cf708fabace.PNG)
if you can add this
![c](https://user-images.githubusercontent.com/36833664/147301485-cdf53a14-a26b-4992-91e6-80ce2da997cd.png)
and Please don't block my issue at https://github.com/firedm/FireDM/issues

![image](https://user-images.githubusercontent.com/36833664/147301864-65efcf06-10a6-4e40-b764-64e2dea878c4.png)

**Comment by Aboghazala** [comment]
@candrapersada 
No problem, 
Now you can report at https://github.com/firedm/FireDM/issues
