### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by hoffstadt** [Aboghazala/AwesomeTkinter#4]
Hey, great work on the widgets. I thought if you needed some inspiration on additional widgets, you can checkout some of these from our GUI library:

![image](https://user-images.githubusercontent.com/39973752/93806482-d1556e00-fc0e-11ea-82f5-afa5387c3479.png)
![image](https://user-images.githubusercontent.com/39973752/93806544-e500d480-fc0e-11ea-91e8-ceb4dbec6952.png)

**Comment by Aboghazala** [comment]
@hoffstadt 
nice work, well done
