### ISSUE TITLE
About the progressbar

### ISSUE THREAD

**Issue by TianT1209** [Aboghazala/AwesomeTkinter#5]
I have a questioin about the progressbar. If I have changed the mode to 'indeterminate', the progressbar don't work. How should I change the code?

**Comment by Aboghazala** [comment]
@TianT1209 
unfortunately both RadialProgressbar and RadialProgressbar3d works only in 'determinate' mode, that's why this option is hard-coded.

**Comment by zocky96** [comment]
and if I want to change the value of the progressbar

**Comment by Aboghazala** [comment]
> and if I want to change the value of the progressbar

@zocky96 
you can use "set()" method to set progressbar or get() to get current value
example:
```
bar = atk.RadialProgressbar(root)
bar.pack()
bar.set(30)
```

**Comment by zocky96** [comment]
Thnx
