### ISSUE TITLE
Issue with the arabic letter ء

### ISSUE THREAD

**Issue by YaserIskobi** [Aboghazala/AwesomeTkinter#9]
Hello,

I am facing issue with this specific letter. Any fix for this?

![issue_screenshot](https://user-images.githubusercontent.com/44681217/140609913-267d7d92-38c2-46a9-8546-aa736fec9460.jpeg)

Thank you

**Comment by Aboghazala** [comment]
@YaserIskobi 
thanks for reporting this 
will check this problem, and try to fix it

**Comment by Aboghazala** [comment]
@YaserIskobi 
unfortunately i couldn't reproduce the problem, here it is a screenshot shows that it works as expected

![image](https://user-images.githubusercontent.com/37757246/140614032-aa697512-7620-4bb3-ae40-1e1be2ecd53b.png)

maybe because your font is different than mine
can you add below code before `root.mainloop()` 

```
from tkinter.font import Font
f = Font(font=lbl['font'])
print(f.actual())
```
and post the output of print statement

**Comment by Aboghazala** [comment]
Also make sure you have the latest version if you have installed thru pip
`pip3 install --upgrade awesometkinter`

**Comment by YaserIskobi** [comment]
@Aboghazala 
Thank you for your quick response.

This is the output for actual font in my side:
{'family': 'Arial', 'size': 20, 'weight': 'normal', 'slant': 'roman', 'underline': 0, 'overstrike': 0}

I also upgraded awesometkinter thru pip but still same issue.
It is the same issue when I put the letter in the text so the entry field don't show the text correctly (see attached)

Thank you again
![entry_screenshot](https://user-images.githubusercontent.com/44681217/140623266-3630dee9-0783-4ab7-8453-2fda72a99fc8.jpeg)
n

**Comment by YaserIskobi** [comment]
Maybe I need to mention that I am using windows 10 as OS

**Comment by Aboghazala** [comment]
@YaserIskobi 
just made a new release with a fix
please upgrade to latest release and check if it works for you

`pip3 install --upgrade awesometkinter`

**Comment by YaserIskobi** [comment]
@Aboghazala 
Yes I confirm it is fixed. Thank you very much for this great Library

**Comment by Aboghazala** [comment]
> @Aboghazala Yes I confirm it is fixed. Thank you very much for this great Library

Great!, you are welcome
